version: "3.7"

services:
  db:
    image: postgres:11-alpine
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
  server:
    build:
      context: .
    environment:
      - COOKPOD_HOST=localhost
      - SECRET_KEY_BASE=ksdhfksds3272hfkjshdf56
      - LIVE_VIEW_SALT=test
      - DB_USERNAME=postgres
      - DB_HOSTNAME=db
      - DB_NAME=postgres
      - DB_PASSWORD=postgres
      - DB_POOL_SIZE=5    